### ISSUE TITLE
无法运行示例

### ISSUE THREAD

**Issue by M69W** [spark-build/transform-antd-theme-variable#2]
## windows10, node: v14.16.0

1.不支持 `rm`
2.临时去除 `rm`，yarn dev 正常, 有个css文件 url 404，App.tsx 中改为 import './App.css'; 
3.接着就下面的异常

```
[vite] Internal server error: Failed to resolve import "../antdThemeVariables" from "src\App.tsx". Does the file exist?
```
<del>从  [.gitignore#L2](https://github.com/spark-build/transform-antd-theme-variable/blob/main/.gitignore#L2) 中看到 `antdThemeVariables.js` 被忽略了</del>

https://github.com/spark-build/transform-antd-theme-variable/commit/484e593e610e61132e04d354623d4eee000d7212#diff-ef8b0273bf1e2d8891a7324974fa3a21fcfa99b34969ae3a74a34e00385fff4fR27
但为什么没有生成？

## macOS 15.7, node: v14.16.0
没有上面的异常，但出现下面报错。
![image](https://user-images.githubusercontent.com/15809201/123500371-3ba0b080-d670-11eb-8b57-3c61f774b277.png)

```
[plugin:vite:import-analysis] Failed to resolve import "./routes" from "src/.vite-plugin-react-auto-config/routes/Router.tsx". Does the file exist?
/Users/z/Desktop/test/transform-antd-theme-variable/example/src/.vite-plugin-react-auto-config/routes/Router.tsx:19:28
17 |  import { useMemo } from "react";
18 |  import { Routes, Route } from "react-router-dom";
19 |  import { getRoutes } from "./routes";
   |                             ^
20 |  function renderRoute(route) {
21 |    const {
    at formatError (/Users/z/Desktop/test/transform-antd-theme-variable/example/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44595:46)
    at TransformContext.error (/Users/z/Desktop/test/transform-antd-theme-variable/example/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44591:19)
    at normalizeUrl (/Users/z/Desktop/test/transform-antd-theme-variable/example/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:70740:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TransformContext.transform (/Users/z/Desktop/test/transform-antd-theme-variable/example/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:70873:57)
    at async Object.transform (/Users/z/Desktop/test/transform-antd-theme-variable/example/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44796:30)
    at async transformRequest (/Users/z/Desktop/test/transform-antd-theme-variable/example/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:60267:29)
    at async viteTransformMiddleware (/Users/z/Desktop/test/transform-antd-theme-variable/example/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:60405:32
Click outside or fix the code to dismiss.
You can also disable this overlay with hmr: { overlay: false } in vite.config.js.
```

**Comment by M69W** [comment]
https://github.com/spark-build/transform-antd-theme-variable/commit/484e593e610e61132e04d354623d4eee000d7212#diff-ef8b0273bf1e2d8891a7324974fa3a21fcfa99b34969ae3a74a34e00385fff4fR27
但为什么没有生成？

**Comment by atzcl** [comment]
1 ~ 3 是因为例子里面使用的 `react vite` 脚手架 `@spark-build/vite-plugin-react-auto-config` 没有适配 `windows`，后面适配了，但是忘了更新这边的依赖了

缺失 `antdThemeVariables.js` 文件是一个故意的操作，因为这里的变量是需要用户自己提供了，当然库里提供了一个命令来便捷生成该变量文件: 
``` 
generateThemeVariable --primary-color=red // -primary-color 为可选参数 
```

为了方便跑示例，我给一键命令加上了生成默认 `antdThemeVariables.js` 文件的命令了

对于后面的缺少 `./routes` 文件的生成，我这边无法复现呢，你可以重新拉取下示例跑一下看看还存不存在这个问题

**Comment by atzcl** [comment]
缺少 ` ./routes ` 异常已修正，应该都没问题了，有问题可以随时回复~
